version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  magma-sessiond:
    image: magmacore/magma-sessiond:v1.9.0
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./sessiond.yml:/etc/magma/sessiond.yml
    ports:
      - "3868:3868"
    networks:
      - magma-ocs-net

networks:
  magma-ocs-net:
    driver: bridge
